version: 2
jobs:
  deploy-CNTK_ImageRecon:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      SERVICE_NAME: CNTK_ImageRecon
      SERVICE_RUN_SCRIPT: run_image_recon_service.py
      SERVICE_TEST_SCRIPT: test_image_recon_service.py
      SNETD_PORT: 7007
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop $DOCKER_CONTAINER_NAME_CNTK || true && nvidia-docker rename $DOCKER_CONTAINER_NAME_CNTK ${DOCKER_CONTAINER_NAME_CNTK}_old || true
            nvidia-docker build \
              --build-arg agent_contract=$AGENT_CONTRACT_CNTK_ImageRecon \
              --build-arg private_key=$PRIVATE_KEY \
              -t $DOCKER_IMAGE_NAME_CNTK https://github.com/arturgontijo/dnn-model-services.git#master:/Services/gRPC/$SERVICE_NAME
            nvidia-docker run --runtime=nvidia \
              --name $DOCKER_CONTAINER_NAME_CNTK \
              --restart unless-stopped \
              -p $SNETD_PORT:$SNETD_PORT \
              -di $DOCKER_IMAGE_NAME_CNTK sh -c "git pull;python3 $SERVICE_RUN_SCRIPT --daemon-conf ."
          EOF
    - run:
        name: Remove Old Docker Container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop ${DOCKER_CONTAINER_NAME_CNTK}_old || true && nvidia-docker rm ${DOCKER_CONTAINER_NAME_CNTK}_old || true
          EOF
    - run:
        name: Test local
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker exec -i $DOCKER_CONTAINER_NAME_CNTK python3 $SERVICE_TEST_SCRIPT test
          EOF

  deploy-I3D_VideoActionRecognition:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      ORG: singnet
      DOCKER_ORG: singularitynet
      DOCKER_IMAGE_NAME: artur_i3d_video_action_recognition
      DOCKER_CONTAINER_NAME: ARTUR_I3D_VideoActionRecognition
      REPO_NAME: dnn-model-services
      SERVICE_NAME: I3D_VideoActionRecognition
      SERVICE_RUN_SCRIPT: run_video_action_recon_service.py
      SERVICE_TEST_SCRIPT: test_video_action_recon_service.py
      SNETD_PORT: 7008
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop $DOCKER_CONTAINER_NAME_I3D || true && nvidia-docker rename $DOCKER_CONTAINER_NAME_I3D ${DOCKER_CONTAINER_NAME_I3D}_old || true
            nvidia-docker build \
              --build-arg agent_contract=$AGENT_CONTRACT_I3D_VideoActionRecognition \
              --build-arg private_key=$PRIVATE_KEY \
              -t $DOCKER_IMAGE_NAME_I3D https://github.com/arturgontijo/dnn-model-services.git#master:/Services/gRPC/$SERVICE_NAME
            nvidia-docker run --runtime=nvidia \
              --name $DOCKER_CONTAINER_NAME_I3D \
              --restart unless-stopped \
              -p $SNETD_PORT:$SNETD_PORT \
              -di $DOCKER_IMAGE_NAME_I3D sh -c "git pull;python3 $SERVICE_RUN_SCRIPT --daemon-conf ."
          EOF
    - run:
        name: Remove Old Docker Container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop ${DOCKER_CONTAINER_NAME_I3D}_old || true && nvidia-docker rm ${DOCKER_CONTAINER_NAME_I3D}_old || true
          EOF
    - run:
        name: Test local
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker exec -i $DOCKER_CONTAINER_NAME_I3D python3 $SERVICE_TEST_SCRIPT test
          EOF

  deploy-ObjectDetection_ImageRecon:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      ORG: singnet
      DOCKER_ORG: singularitynet
      DOCKER_IMAGE_NAME: artur_meta_service
      DOCKER_CONTAINER_NAME: ARTUR_ObjectDetection_ImageRecon
      REPO_NAME: dnn-model-services
      SERVICE_NAME: Meta_Services/ObjectDetection_ImageRecon
      SERVICE_RUN_SCRIPT: run_ObjectDetection_ImageRecon_service.py
      SERVICE_TEST_SCRIPT: test_ObjectDetection_ImageRecon_service.py
      SNETD_PORT: 7009
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop $DOCKER_CONTAINER_NAME_META || true && nvidia-docker rename $DOCKER_CONTAINER_NAME_META ${DOCKER_CONTAINER_NAME_META}_old || true
            nvidia-docker build \
              --build-arg agent_contract=$AGENT_CONTRACT_ObjectDetection_ImageRecon \
              --build-arg private_key=$PRIVATE_KEY \
              -t $DOCKER_IMAGE_NAME_META https://github.com/arturgontijo/dnn-model-services.git#master:/Services/gRPC/$SERVICE_NAME
            nvidia-docker run --runtime=nvidia \
              --name $DOCKER_CONTAINER_NAME_META \
              --restart unless-stopped \
              -p $SNETD_PORT:$SNETD_PORT \
              -di $DOCKER_IMAGE_NAME_META sh -c "git pull;python3 $SERVICE_RUN_SCRIPT --daemon-conf ."
          EOF
    - run:
        name: Remove Old Docker Container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop ${DOCKER_CONTAINER_NAME_META}_old || true && nvidia-docker rm ${DOCKER_CONTAINER_NAME_META}_old || true
          EOF
    - run:
        name: Test local
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker exec -i $DOCKER_CONTAINER_NAME_META python3 $SERVICE_TEST_SCRIPT test
          EOF

  deploy-S2VT_VideoCaptioning:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      ORG: singnet
      DOCKER_ORG: singularitynet
      DOCKER_IMAGE_NAME: artur_s2vt_video_captioning
      DOCKER_CONTAINER_NAME: ARTUR_S2VT_VideoCaptioning
      REPO_NAME: dnn-model-services
      SERVICE_NAME: S2VT_VideoCaptioning
      SERVICE_RUN_SCRIPT: run_video_cap_service.py
      SERVICE_TEST_SCRIPT: test_video_cap_service.py
      SNETD_PORT: 7004
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop $DOCKER_CONTAINER_NAME_S2VT || true && nvidia-docker rename $DOCKER_CONTAINER_NAME_S2VT ${DOCKER_CONTAINER_NAME_S2VT}_old || true
            nvidia-docker build \
              --build-arg agent_contract=$AGENT_CONTRACT_S2VT_VideoCaptioning \
              --build-arg private_key=$PRIVATE_KEY \
              -t $DOCKER_IMAGE_NAME_S2VT https://github.com/arturgontijo/dnn-model-services.git#master:/Services/gRPC/$SERVICE_NAME
            nvidia-docker run --runtime=nvidia \
              --name $DOCKER_CONTAINER_NAME_S2VT \
              --restart unless-stopped \
              -p $SNETD_PORT:$SNETD_PORT \
              -di $DOCKER_IMAGE_NAME_S2VT sh -c "git pull;python $SERVICE_RUN_SCRIPT --daemon-conf ."
          EOF
    - run:
        name: Remove Old Docker Container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop ${DOCKER_CONTAINER_NAME_S2VT}_old || true && nvidia-docker rm ${DOCKER_CONTAINER_NAME_S2VT}_old || true
          EOF
    - run:
        name: Test local
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker exec -i $DOCKER_CONTAINER_NAME_S2VT python $SERVICE_TEST_SCRIPT test
          EOF

  deploy-YOLOv3_ObjectDetection:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
      ORG: singnet
      DOCKER_ORG: singularitynet
      DOCKER_IMAGE_NAME: artur_yolov3_object_detection
      DOCKER_CONTAINER_NAME: ARTUR_YOLOv3_ObjectDetection
      REPO_NAME: dnn-model-services
      SERVICE_NAME: YOLOv3_ObjectDetection
      SERVICE_RUN_SCRIPT: run_object_detection_service.py
      SERVICE_TEST_SCRIPT: test_object_detection_service.py
      SNETD_PORT: 7005
    steps:
    - run:
        name: Deploy Over SSH
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop $DOCKER_CONTAINER_NAME_YOLOv3 || true && nvidia-docker rename $DOCKER_CONTAINER_NAME_YOLOv3 ${DOCKER_CONTAINER_NAME_YOLOv3}_old || true
            nvidia-docker build \
              --build-arg agent_contract=$AGENT_CONTRACT_YOLOv3_ObjectDetection \
              --build-arg private_key=$PRIVATE_KEY \
              -t $DOCKER_IMAGE_NAME_YOLOv3 https://github.com/arturgontijo/dnn-model-services.git#master:/Services/gRPC/$SERVICE_NAME
            nvidia-docker run --runtime=nvidia \
              --name $DOCKER_CONTAINER_NAME_YOLOv3 \
              --restart unless-stopped \
              -p $SNETD_PORT:$SNETD_PORT \
              -di $DOCKER_IMAGE_NAME_YOLOv3 sh -c "git pull;python3 $SERVICE_RUN_SCRIPT --daemon-conf ."
          EOF
    - run:
        name: Remove Old Docker Container
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker stop ${DOCKER_CONTAINER_NAME_YOLOv3}_old || true && nvidia-docker rm ${DOCKER_CONTAINER_NAME_YOLOv3}_old || true
          EOF
    - run:
        name: Test local
        command: |
          ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST << EOF
            nvidia-docker exec -i $DOCKER_CONTAINER_NAME_YOLOv3 python3 $SERVICE_TEST_SCRIPT test
          EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-CNTK_ImageRecon
      - deploy-I3D_VideoActionRecognition
      #- deploy-ObjectDetection_ImageRecon
      - deploy-S2VT_VideoCaptioning
      - deploy-YOLOv3_ObjectDetection